import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import MouseCircle from "./components/MouseCircle";
import BackgroundCanvas from "./components/three/BackgroundCanvas";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Michel Busse | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MouseCircle />
        <BackgroundCanvas />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
