name: Deploy

on:
  push

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SERVER_USER }}
          SSH_KEY: ${{ secrets.ID_RSA }}
          SSH_HOST: ${{ secrets.SERVER_IP }}
          SSH_PORT: ${{ secrets.SERVER_PORT }}

      - name: Stop the server
        run: ssh staging 'sudo systemctl stop my-application'

      - name: Check out the source
        run: ssh staging 'cd my-application && git fetch && git reset --hard origin/master'

      - name: Start the server
        if: ${{ always() }}
        run: ssh staging 'sudo systemctl start my-application'

      - name: Deploy to Server
        run: |
          ssh staging 'cd /home/schale/development/michelbusse-homepage; bash' < deploy.sh

      - name: Start Docker Compose
        run: |
          ssh staging 'cd /home/schale/development/michelbusse-homepage && docker compose up -d --build'