name: Deploy

on:
  push

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SERVER_USER }}
          SSH_KEY: ${{ secrets.ID_RSA }}
          SSH_HOST: ${{ secrets.SERVER_IP }}
          SSH_PORT: ${{ secrets.SERVER_PORT }}

      - name: Deploy to Server
        run: |
          ssh deploy 'echo "hey"'

      - name: Start Docker Compose
        run: |
          ssh deploy 'cd /home/schale/development/michelbusse-homepage && docker compose up -d --build'